### ISSUE TITLE
Cannot see the results

### ISSUE THREAD

**Issue by manuelcaeiro** [peberlein/WEE#4]
I'm new to Euphoria, so I may be making some stupid mistake...
- I open wee using "eui wee". 
- I write and save a simple loop:
for i = 1 to 10 do
    ? i
end for 

- But when I run the loop, a console flashes (appears and disappears instantaneously) and I cannot see the result.

On the other hand, I write the same loop on edx.ex oppened inside a console, esc to menu, press eui (run), the console comes over the editor and shows the result (i.e., prints a column of number 1 to 10). I hit esc and get back to the editor.

**Comment by peberlein** [comment]
On the Run menu, check the option "Wait for Keypress after Run in Terminal"

**Comment by manuelcaeiro** [comment]
![wee_ss_w_runmenu](https://user-images.githubusercontent.com/35598087/39241758-e023ce12-487f-11e8-8750-d58ce2b086a3.JPG)

**Comment by manuelcaeiro** [comment]
I don't seem to have that option...
![wee_ss_w_runmenu](https://user-images.githubusercontent.com/35598087/39241912-4eae4916-4880-11e8-91a4-c3005c4887ef.JPG)

**Comment by peberlein** [comment]
My apologies, I mistakenly assumed Linux when I saw "eui".  Wee for Linux has that option, but Windows does not. The simplest solution is to put "include std/console.e" with your includes and "maybe_any_key()" as the last statement of your program.

**Comment by manuelcaeiro** [comment]
It works fine*, and that's enough for now, while learning.
Thank you very much for your help and for your software.
Best regards.

*Even if WEE is opened  using >start "eui" "wee.exw", which allows to close the console keeping the editor open.
