### ISSUE TITLE
Crash when attempting to start WEE editor via EUI

### ISSUE THREAD

**Issue by srb623** [peberlein/WEE#6]
I have downloaded updater.ex and executed it as per your instructions and now have a set of wee related files.  When I type in 'eui wee' as per your instructions it pops up a dialog box containing the message:

> Houston, Wee've had a problem.
The editor crashed and is closing now.

I then get an pile of error messages to the console which are as follows:

> .../EuGTK/GtkEngine.e:226 in function create() 
subscript value 1 is out of bounds, reading from a sequence of length 0 - in subscript #1 of 'p1' 

> ... called from .../ui_gtk.e:1225 in procedure ui_refresh_file_menu()  

> ... called from .../ui_gtk.e:1498 

> --> See ex.err 

However, if I compile the wee.exw file with euc and run the resulting wee executable then it compiles and then starts up OK.

I am running Debian Linux (testing/buster) on a 64 bit machine.  My version of eui and euc are as per the following:

> Euphoria to C Translator v4.1.0 development
   64-bit Linux, Using System Memory
   Revision Date: 2015-02-02 14:18:53, Id: 5861:57179171dbed

> Euphoria Interpreter v4.1.0 development
   64-bit Linux, Using System Memory
   Revision Date: 2015-02-02 14:18:53, Id: 5861:57179171dbed

Am I doing something wrong ?  Any assistance in this matter would be much appreciated.

**Comment by peberlein** [comment]
What is the contents of your ~/.wee_conf?  I suspect the recent_file entries may have gotten corrupted, but not sure how.  Do you still have the ex.err?  I realize this was over a month ago, sorry about that.

**Comment by srb623** [comment]
Sorry for not adding a nrw comment to this but as I had it working via a compile via EUC I had forgotten about it.  You were correct re the wee_conf file.  I deleted this and then re tested via EUI and all works find via that method now.  So happy to close this one.
